<a href="https://colab.research.google.com/github/ikkoawinata/ikkoawinata.github.io/blob/ikkoawinata.github.io/SAINS%20KOMPUTASI%20(Tugas)Teknik_Komputasi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from numpy import array
print("Praktek (1) : Lakukan operasi penjumlahan pada Matrik A dan B")
print("----------------------------")
MatrikA = array([[8.,5.,6],\
                [4.,5.,2],\
                [9.,7.,6]])
print("Matriks A : ")
print (MatrikA)
print()
MatrikB = array([[5.,5.,6],\
    [4.,5.,2],\
        [9.,7.,6]])
print("Matriks B : ")
print (MatrikB)

print()
print("Hasil Penjumlahan Matriks A + Matriks B : ")
hasil = MatrikA + MatrikB
print(hasil)

print()
print("Praktek (2) : Lakukan operasi pengurangan pada Matrik A dan B")
print("----------------------------")
MatrikA = array([[8.,5.,6],\
                [4.,5.,2],\
                [9.,7.,6]])
print("Matriks A : ")
print (MatrikA)
print()
MatrikB = array([[5.,5.,6],\
    [4.,5.,2],\
        [9.,7.,6]])
print("Matriks B : ")
print (MatrikB)

print()
print("Hasil pengurangan Matriks A + Matriks B : ")
hasil = MatrikA - MatrikB
print(hasil)

Praktek (1) : Lakukan operasi penjumlahan pada Matrik A dan B
----------------------------
Matriks A : 
[[8. 5. 6.]
 [4. 5. 2.]
 [9. 7. 6.]]

Matriks B : 
[[5. 5. 6.]
 [4. 5. 2.]
 [9. 7. 6.]]

Hasil Penjumlahan Matriks A + Matriks B : 
[[13. 10. 12.]
 [ 8. 10.  4.]
 [18. 14. 12.]]

Praktek (2) : Lakukan operasi pengurangan pada Matrik A dan B
----------------------------
Matriks A : 
[[8. 5. 6.]
 [4. 5. 2.]
 [9. 7. 6.]]

Matriks B : 
[[5. 5. 6.]
 [4. 5. 2.]
 [9. 7. 6.]]

Hasil pengurangan Matriks A + Matriks B : 
[[3. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
from numpy import array , zeros
print("Praktek (3) : Apa luaran (output) dari perintah berikut !")
A = array([[3.,8.,5],\
           [6.,4.,7]]) # berukuran 2x3
print()
C = array ([[9.,5.,3],\
            [7.,2.,1]]) #C berukuran 2x3
n = 2
m = 3
D = zeros((n,m))

for i in range (0,n):
  for j in range ( 0,m):
    D[i][j] = A[i][j] + C[i][j]
    print( D)

Praktek (3) : Apa luaran (output) dari perintah berikut !

 [[12.  0.  0.]
 [ 0.  0.  0.]]
 [[12. 13.  0.]
 [ 0.  0.  0.]]
 [[12. 13.  8.]
 [ 0.  0.  0.]]
 [[12. 13.  8.]
 [13.  0.  0.]]
 [[12. 13.  8.]
 [13.  6.  0.]]
 [[12. 13.  8.]
 [13.  6.  8.]]


In [ ]:
from numpy import array, zeros
print("Praktek (4): Operasi komputasi apa yang dilakukan oleh listing ")
print("berikut ini dan tulis outputnya !")
A = array([[3.,8.,5.],\
           [6.,4.,7.]])# A berukuran 2x3
print("")
B = array([[1.,3.],\
           [5.,9.],\
           [2.,4.]]) #B berukuran 3x2
n = 2 # jumlah baris matrik A
m = 3 # jumlah kolom matrik A sekaligus jumlah baris matrik B
p = 2 #jumlah kolom matriks B
E = zeros((n,p))
for i in range (0,n):
  for j in range (0,p):
     for k in range (0,m):
      E[i][j] = E[i][j]+A[i][j] * B[k][j]
      print(E)

Praktek (4): Operasi komputasi apa yang dilakukan oleh listing 
berikut ini dan tulis outputnya !

[[3. 0.]
 [0. 0.]]
[[18.  0.]
 [ 0.  0.]]
[[24.  0.]
 [ 0.  0.]]
[[24. 24.]
 [ 0.  0.]]
[[24. 96.]
 [ 0.  0.]]
[[ 24. 128.]
 [  0.   0.]]
[[ 24. 128.]
 [  6.   0.]]
[[ 24. 128.]
 [ 36.   0.]]
[[ 24. 128.]
 [ 48.   0.]]
[[ 24. 128.]
 [ 48.  12.]]
[[ 24. 128.]
 [ 48.  48.]]
[[ 24. 128.]
 [ 48.  64.]]


In [ ]:
from numpy import array, zeros
print("Praktek (5): Operasi komputasi apa yang dilakukan oleh listing ")
print("berikut ini dan tulis outputnya !")
A1 = array([[3.,8.,5.],\
            [6.,4.,7.]]) #A1 berukuran 2x3
x = array([[2.],\
           [3.],\
           [4.]]) #vector x berukuran 3x1
n = 2 #jumlah baris matriks A
m = 3 #jumlah kolom matriks A sekaligus jumlah baris vector X\
E = zeros((n,1))
for i in range(0,n):
  for k in range(0,m):
    E[i][0] = E[i][0] + A1 [i][k]*x[k][0]
    print(E)


Praktek (5): Operasi komputasi apa yang dilakukan oleh listing 
berikut ini dan tulis outputnya !
[[6.]
 [0.]]
[[30.]
 [ 0.]]
[[50.]
 [ 0.]]
[[50.]
 [12.]]
[[50.]
 [24.]]
[[50.]
 [52.]]


In [ ]:
from numpy import array
print("Praktek (6): Operasi komputasi apa yang dilakukan oleh listing ")
print("berikut ini dan tulis outputnya !")

x = [[20, 9],
     [8, 5],
     [9, 8]]

result = [[0, 0, 0],
          [0, 0, 0]]

# Iterasi baris
for i in range(len(x)):
    # Iterasi kolom
    for j in range(len(x[0])):
        result[j][i] = x[i][j]

print("hasilnya adalah : ")
for r in result:
  print(r)


Praktek (6): Operasi komputasi apa yang dilakukan oleh listing 
berikut ini dan tulis outputnya !
hasilnya adalah : 
[20, 8, 9]
[9, 5, 8]


In [ ]:
print("Praktek (7): Operasi komputasi apa yang dilakukan oleh listing ")
print("berikut ini dan tulis outputnya !")
a = 5
b = 6
c = 7
y = a * 2 + b * 3 + c * 4
print("hasil dari (y =  a * 2 + b * 3 + c * 4 ) adalah : ")
print(y)



Praktek (7): Operasi komputasi apa yang dilakukan oleh listing 
berikut ini dan tulis outputnya !
hasil dari (y =  a * 2 + b * 3 + c * 4 ) adalah : 
56


In [ ]:
print("Praktek (8): Operasi komputasi apa yang dilakukan oleh listing ")
print("berikut ini dan tulis outputnya !")
def rumus (a,b):
  y = 25*a+60*b
  return y
rumus (2,3)


Praktek (8): Operasi komputasi apa yang dilakukan oleh listing 
berikut ini dan tulis outputnya !


230

In [ ]:
print("Praktek (9): Operasi komputasi apa yang dilakukan oleh listing ")
print("berikut ini dan tulis outputnya !")
class Matematika():
    def rumus1(a, b, c):
        y = a * 2 + b * 3 + c * 4
        return y
print("hasilnya adalah " , Matematika.rumus1(5, 6, 7))



Praktek (9): Operasi komputasi apa yang dilakukan oleh listing 
berikut ini dan tulis outputnya !
hasilnya adalah  56


In [ ]:
print("Praktek (10): Operasi komputasi apa yang dilakukan oleh listing ")
print("berikut ini dan tulis outputnya !")
class Matematika():
    def rumus2(a, b, c):
        x = a * 2 + b * 3 + c * 4
        y = a*b*c
        return x,y
print("hasilnya adalah : " , Matematika.rumus2(5, 6, 7))

Praktek (10): Operasi komputasi apa yang dilakukan oleh listing 
berikut ini dan tulis outputnya !
hasilnya adalah :  (56, 210)


In [ ]:
print("Praktek (11): Operasi komputasi apa yang dilakukan oleh listing ")
print("berikut ini dan tulis outputnya !")
class Matematika():
    def rumus3(a, b, c):
        x = a * 6 + b * 8 + c * 8
        return x

    def rumus4(a, b, c):
        x = a * 2 + b * 3 + c * 4
        y = a * b * c
        return x, y

print("hasil rumus 3 adalah = " , Matematika.rumus3(1, 1, 1))
print("hasil rumus 4 adalah = " , Matematika.rumus4(2, 2, 2))


Praktek (11): Operasi komputasi apa yang dilakukan oleh listing 
berikut ini dan tulis outputnya !
hasil rumus 3 adalah =  22
hasil rumus 4 adalah =  (18, 8)


In [ ]:
print("Praktek (12): Operasi komputasi apa yang dilakukan oleh listing ")
print("berikut ini dan tulis outputnya !")
def rumus3 (a,b,c):
  x = a*6+b*8+c*8
  return x
print("hasilnya adalah : " ,rumus3(1,1,1))


Praktek (12): Operasi komputasi apa yang dilakukan oleh listing 
berikut ini dan tulis outputnya !
hasilnya adalah :  22
